spring:
  application:
    name: movies
  redis:
    host: localhost
    port: 6379

rest:
  movies:
    url-base: https://directa24-movies.wiremockapi.cloud
    uri: /api/movies/search

logging:
  level:
    org.apache.hc.client5.http: DEBUG
